# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
dRoute Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the dRoute routing model.

This module registers dRoute-specific configuration components with the
ModelRegistry, enabling the core config system to remain model-agnostic.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations. All defaults are maintained in DRouteConfig
(model_configs.py) for single source of truth.
"""

from typing import Any, Dict

from symfluence.models.base import AutoGeneratedConfigAdapter


class DRouteConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for dRoute model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from DRouteConfig
    Pydantic model. Only custom validation logic is implemented here.
    """

    def __init__(self, model_name: str = 'DROUTE'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return dRoute Pydantic configuration schema."""
        from symfluence.core.config.models.model_configs import DRouteConfig
        return DRouteConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """
        Validate dRoute-specific configuration.

        Performs validation checks specific to dRoute:
        - Routing method compatibility
        - AD backend availability
        - Topology format validation
        """
        # Validate routing method
        routing_method = config.get('routing_method', 'muskingum_cunge')
        valid_methods = ['muskingum_cunge', 'irf', 'lag', 'diffusive_wave', 'kwt']
        if routing_method not in valid_methods:
            raise ValueError(
                f"Invalid routing_method '{routing_method}'. "
                f"Must be one of: {valid_methods}"
            )

        # Validate AD backend if gradients enabled
        enable_gradients = config.get('enable_gradients', False)
        ad_backend = config.get('ad_backend', 'codipack')
        if enable_gradients:
            valid_backends = ['codipack', 'enzyme']
            if ad_backend not in valid_backends:
                raise ValueError(
                    f"Invalid ad_backend '{ad_backend}' for gradient computation. "
                    f"Must be one of: {valid_backends}"
                )

        # Validate topology format
        topology_format = config.get('topology_format', 'netcdf')
        valid_formats = ['netcdf', 'geojson', 'csv']
        if topology_format not in valid_formats:
            raise ValueError(
                f"Invalid topology_format '{topology_format}'. "
                f"Must be one of: {valid_formats}"
            )
