# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
dRoute Model Configuration.

Provides the configuration schema (:class:`DRouteConfig`), adapter, and validation
for the dRoute routing model.

Following the JAX-model plugin pattern, the dRoute package OWNS its own Pydantic
configuration schema and registers it with SYMFLUENCE via
``model_manifest(config_schema=DRouteConfig)`` (see :func:`droute.register`). The schema
was previously carried framework-side in
``symfluence.core.config.models.model_configs_routing``; it now lives here so the package
is self-contained.

:class:`DRouteConfigAdapter` (an ``AutoGeneratedConfigAdapter``) derives defaults and
transformers from the Pydantic Field declarations below, so DRouteConfig is the single
source of truth for dRoute config defaults.
"""

from typing import Any, Dict, Literal

from pydantic import BaseModel, Field
from symfluence.core.config.models.base import FROZEN_CONFIG
from symfluence.models.base import AutoGeneratedConfigAdapter


class DRouteConfig(BaseModel):
    """dRoute routing model configuration.

    dRoute is a C++ river routing library with Python bindings that offers:
    - Multiple routing methods (Muskingum-Cunge, IRF, Lag, Diffusive Wave, KWT, Saint-Venant)
    - Native automatic differentiation for gradient-based calibration
    - mizuRoute-compatible network topology format
    - Inline + subgrid lake routing and transfer-function parameter regionalization
    """
    model_config = FROZEN_CONFIG

    # Execution settings
    execution_mode: Literal['python', 'subprocess'] = Field(
        default='python',
        alias='DROUTE_EXECUTION_MODE',
        description='Execution mode: python API (preferred) or subprocess fallback'
    )
    install_path: str = Field(default='default', alias='DROUTE_INSTALL_PATH')
    exe: str = Field(default='droute', alias='DROUTE_EXE')
    settings_path: str = Field(default='default', alias='SETTINGS_DROUTE_PATH')

    # Routing configuration
    routing_method: Literal['muskingum_cunge', 'irf', 'lag', 'diffusive_wave', 'kwt', 'saint_venant'] = Field(
        default='muskingum_cunge',
        alias='DROUTE_ROUTING_METHOD',
        description='Routing scheme to use'
    )
    routing_dt: int = Field(
        default=3600,
        alias='DROUTE_ROUTING_DT',
        ge=60,
        le=86400,
        description='Routing timestep in seconds (Muskingum-Cunge path)'
    )

    # Saint-Venant + lakes settings
    routing_dt_hours: float = Field(
        default=12.0,
        alias='DROUTE_ROUTING_DT_HOURS',
        description='Saint-Venant routing timestep in hours (the daily window is sub-stepped to this)'
    )
    sv_nodes: int = Field(
        default=4,
        alias='DROUTE_SV_NODES',
        description='Number of finite-volume nodes per reach in the Saint-Venant solver'
    )
    runoff_cap: float = Field(
        default=50.0,
        alias='DROUTE_RUNOFF_CAP',
        description='Cap (m^3/s) applied to per-segment SUMMA runoff before routing'
    )
    route_start: str = Field(
        default='2010-01-01',
        alias='DROUTE_ROUTE_START',
        description='Start of the routing (spin-up) window for the Saint-Venant path'
    )
    regionalization: Literal['lumped', 'transfer_function', 'zones', 'distributed'] = Field(
        default='lumped',
        alias='DROUTE_REGIONALIZATION',
        description='Parameter regionalization method (Saint-Venant calibrations default to transfer_function)'
    )

    # Gradient/AD settings
    enable_gradients: bool = Field(
        default=False,
        alias='DROUTE_ENABLE_GRADIENTS',
        description='Enable automatic differentiation for gradient-based calibration'
    )
    ad_backend: Literal['codipack', 'enzyme'] = Field(
        default='codipack',
        alias='DROUTE_AD_BACKEND',
        description='AD backend (requires dRoute compiled with AD support)'
    )

    # Topology configuration
    topology_file: str = Field(default='topology.nc', alias='DROUTE_TOPOLOGY_FILE')
    topology_format: Literal['netcdf', 'geojson', 'csv'] = Field(
        default='netcdf',
        alias='DROUTE_TOPOLOGY_FORMAT'
    )
    config_file: str = Field(default='droute_config.yaml', alias='DROUTE_CONFIG_FILE')

    # Integration settings
    from_model: str = Field(
        default='default',
        alias='DROUTE_FROM_MODEL',
        description='Source model for runoff input (SUMMA, FUSE, GR, etc.)'
    )

    # Output settings
    experiment_output: str = Field(default='default', alias='EXPERIMENT_OUTPUT_DROUTE')
    experiment_log: str = Field(default='default', alias='EXPERIMENT_LOG_DROUTE')

    # Calibration settings
    params_to_calibrate: str = Field(
        default='velocity,diffusivity',
        alias='DROUTE_PARAMS_TO_CALIBRATE'
    )
    calibrate: bool = Field(default=False, alias='CALIBRATE_DROUTE')
    timeout: int = Field(default=3600, alias='DROUTE_TIMEOUT', ge=60, le=86400)


class DRouteConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for dRoute model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from the :class:`DRouteConfig`
    Pydantic model. Only custom validation logic is implemented here.
    """

    def __init__(self, model_name: str = 'DROUTE'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return the dRoute Pydantic configuration schema (package-owned)."""
        return DRouteConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """
        Validate dRoute-specific configuration.

        Performs validation checks specific to dRoute:
        - Routing method compatibility
        - AD backend availability
        - Topology format validation
        """
        # Validate routing method
        routing_method = config.get('routing_method', 'muskingum_cunge')
        valid_methods = ['muskingum_cunge', 'irf', 'lag', 'diffusive_wave', 'kwt', 'saint_venant']
        if routing_method not in valid_methods:
            raise ValueError(
                f"Invalid routing_method '{routing_method}'. "
                f"Must be one of: {valid_methods}"
            )

        # Validate AD backend if gradients enabled
        enable_gradients = config.get('enable_gradients', False)
        ad_backend = config.get('ad_backend', 'codipack')
        if enable_gradients:
            valid_backends = ['codipack', 'enzyme']
            if ad_backend not in valid_backends:
                raise ValueError(
                    f"Invalid ad_backend '{ad_backend}' for gradient computation. "
                    f"Must be one of: {valid_backends}"
                )

        # Validate topology format
        topology_format = config.get('topology_format', 'netcdf')
        valid_formats = ['netcdf', 'geojson', 'csv']
        if topology_format not in valid_formats:
            raise ValueError(
                f"Invalid topology_format '{topology_format}'. "
                f"Must be one of: {valid_formats}"
            )
